<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/config/config.php';
require_once dirname(__DIR__) . '/includes/Database.php';
session_name(SESSION_NAME);
session_start();

$pageTitle = 'Panelim';
$currentPage = 'dashboard';
$clientId = (int) ($_SESSION['client_id'] ?? 0);
include 'includes/header.php';

try {
    $stats = [
        'services' => (int) Database::fetchColumn("SELECT COUNT(*) FROM services WHERE client_id = ? AND status = 'active'", [$clientId]),
        'invoices_unpaid' => (int) Database::fetchColumn("SELECT COUNT(*) FROM invoices WHERE client_id = ? AND status = 'unpaid'", [$clientId]),
        'tickets_open' => (int) Database::fetchColumn("SELECT COUNT(*) FROM tickets WHERE client_id = ? AND status IN ('open', 'answered', 'customer-reply')", [$clientId]),
        'domains' => (int) Database::fetchColumn("SELECT COUNT(*) FROM domains WHERE client_id = ?", [$clientId]),
        'total_spent' => (float) Database::fetchColumn("SELECT COALESCE(SUM(total), 0) FROM invoices WHERE client_id = ? AND status = 'paid'", [$clientId]),
    ];
    $recentServices = Database::fetchAll("SELECT s.*, p.name AS product_name FROM services s LEFT JOIN products p ON s.product_id = p.id WHERE s.client_id = ? ORDER BY s.created_at DESC LIMIT 5", [$clientId]);
    $unpaidInvoices = Database::fetchAll("SELECT * FROM invoices WHERE client_id = ? AND status = 'unpaid' ORDER BY due_date ASC LIMIT 4", [$clientId]);
    $recentTickets = Database::fetchAll("SELECT * FROM tickets WHERE client_id = ? ORDER BY created_at DESC LIMIT 3", [$clientId]);
} catch (Throwable $e) {
    $stats = ['services' => 0, 'invoices_unpaid' => 0, 'tickets_open' => 0, 'domains' => 0, 'total_spent' => 0];
    $recentServices = $unpaidInvoices = $recentTickets = [];
}
$firstName = trim((string) ($currentClient['first_name'] ?? 'Müşteri'));
$currency = static fn(float $amount): string => number_format($amount, 2, ',', '.') . ' ₺';
$serviceStatus = ['active' => ['Aktif', 'success'], 'pending' => ['Beklemede', 'warning'], 'suspended' => ['Askıda', 'danger']];
$ticketStatus = ['open' => ['Açık', 'warning'], 'answered' => ['Yanıtlandı', 'success'], 'customer-reply' => ['Yanıt bekleniyor', 'info'], 'closed' => ['Kapalı', 'gray']];
?>
<style>
    .cp-dashboard{max-width:1400px;margin:0 auto}.cp-hero{position:relative;overflow:hidden;isolation:isolate;display:grid;grid-template-columns:1fr auto;gap:28px;align-items:end;padding:clamp(27px,4vw,48px);border:1px solid rgba(107, 163, 251,.3);border-radius:24px;background:linear-gradient(118deg,#10346f 0%,#164bab 45%,#0f766e 130%);box-shadow:0 24px 55px rgba(0,0,0,.17)}.cp-hero:after{content:'';position:absolute;z-index:-1;right:-100px;top:-190px;width:480px;height:480px;border:70px solid rgba(255,255,255,.08);border-radius:50%}.cp-kicker{display:flex;align-items:center;gap:8px;color:#c7d2fe;font-size:12px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.cp-kicker i{color:#6ee7b7}.cp-hero h1{margin:14px 0 9px;font-size:clamp(28px,3.6vw,43px);letter-spacing:-.04em}.cp-hero p{max-width:600px;margin:0;color:#e0e7ff;font-size:15px;line-height:1.7}.cp-hero-actions{display:flex;gap:11px;flex-wrap:wrap;margin-top:25px}.cp-action{display:inline-flex;align-items:center;gap:9px;padding:12px 15px;border:1px solid rgba(255,255,255,.3);border-radius:11px;color:#fff;text-decoration:none;font-size:13px;font-weight:700;transition:.2s}.cp-action:hover{transform:translateY(-2px);background:rgba(255,255,255,.14)}.cp-action--solid{border-color:#fff;background:#fff;color:#164bab}.cp-credit{min-width:190px;padding:20px;border:1px solid rgba(255,255,255,.2);border-radius:16px;background:rgba(15,23,42,.2);backdrop-filter:blur(8px)}.cp-credit span{display:block;color:#c7d2fe;font-size:12px}.cp-credit strong{display:block;margin:7px 0 11px;font-size:25px;letter-spacing:-.04em}.cp-credit small{display:flex;align-items:center;gap:6px;color:#a7f3d0;font-size:12px}
    .cp-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:18px 0 38px}.cp-metric{display:block;padding:19px;border:1px solid rgba(255,255,255,.1);border-radius:16px;background:var(--card-bg);color:#fff;text-decoration:none;transition:.2s}.cp-metric:hover{transform:translateY(-3px);border-color:rgba(107, 163, 251,.65)}.cp-metric-top{display:flex;justify-content:space-between;align-items:center;color:var(--text-muted);font-size:12px;font-weight:600}.cp-metric-icon{display:grid;place-items:center;width:34px;height:34px;border-radius:10px;background:rgba(107, 163, 251,.17);color:#a5b4fc}.cp-metric:nth-child(2) .cp-metric-icon{background:rgba(239,68,68,.14);color:#fca5a5}.cp-metric:nth-child(3) .cp-metric-icon{background:rgba(245,158,11,.14);color:#fcd34d}.cp-metric:nth-child(4) .cp-metric-icon{background:rgba(16,185,129,.14);color:#6ee7b7}.cp-metric-value{margin-top:16px;font-size:28px;font-weight:800;letter-spacing:-.04em}.cp-metric-text{margin-top:3px;color:var(--text-muted);font-size:12px}
    .cp-layout{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(280px,.9fr);gap:20px}.cp-card{overflow:hidden;margin-bottom:20px;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:var(--card-bg)}.cp-card-head{display:flex;justify-content:space-between;align-items:center;padding:20px 22px;border-bottom:1px solid rgba(255,255,255,.08)}.cp-card-title{display:flex;align-items:center;gap:10px;font-size:16px;font-weight:700}.cp-card-title i{color:#a5b4fc}.cp-link{color:#a5b4fc;font-size:12px;font-weight:700;text-decoration:none}.cp-link:hover{text-decoration:underline}.cp-list{padding:3px 22px}.cp-row{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:15px 0;border-bottom:1px solid rgba(255,255,255,.07)}.cp-row:last-child{border:0}.cp-row-main{display:flex;align-items:center;min-width:0;gap:12px}.cp-row-icon{display:grid;place-items:center;flex:0 0 39px;width:39px;height:39px;border-radius:11px;background:rgba(107, 163, 251,.15);color:#a5b4fc}.cp-row h3{overflow:hidden;margin:0 0 4px;font-size:13px;text-overflow:ellipsis;white-space:nowrap}.cp-row p{margin:0;color:var(--text-muted);font-size:12px}.cp-badge{display:inline-flex;align-items:center;gap:6px;padding:6px 9px;border-radius:99px;font-size:11px;font-weight:700;white-space:nowrap}.cp-badge:before{width:6px;height:6px;border-radius:50%;content:''}.cp-badge.success{background:rgba(16,185,129,.12);color:#6ee7b7}.cp-badge.success:before{background:#10b981}.cp-badge.warning{background:rgba(245,158,11,.12);color:#fcd34d}.cp-badge.warning:before{background:#f59e0b}.cp-badge.danger{background:rgba(239,68,68,.12);color:#fca5a5}.cp-badge.danger:before{background:#ef4444}.cp-badge.info{background:rgba(59,130,246,.12);color:#93c5fd}.cp-badge.info:before{background:#3b82f6}.cp-badge.gray{background:rgba(148,163,184,.12);color:#cbd5e1}.cp-badge.gray:before{background:#94a3b8}.cp-invoice-amount{text-align:right;color:#fca5a5;font-size:14px;font-weight:800}.cp-invoice-amount small{display:block;margin-top:4px;color:var(--text-muted);font-size:11px;font-weight:400}
    .cp-quick{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:18px}.cp-quick a{padding:15px 12px;border:1px solid rgba(255,255,255,.1);border-radius:13px;color:#e2e8f0;text-align:center;text-decoration:none;font-size:12px;font-weight:700;transition:.2s}.cp-quick a:hover{border-color:#6ba3fb;background:rgba(36, 116, 245,.14);color:#fff;transform:translateY(-2px)}.cp-quick i{display:block;margin-bottom:9px;color:#a5b4fc;font-size:18px}.cp-ticket{display:block;padding:14px 18px;border-bottom:1px solid rgba(255,255,255,.07);color:inherit;text-decoration:none;transition:.2s}.cp-ticket:last-child{border:0}.cp-ticket:hover{background:rgba(255,255,255,.035)}.cp-ticket-top{display:flex;justify-content:space-between;gap:10px;align-items:start}.cp-ticket h3{margin:0;line-height:1.4;font-size:13px}.cp-ticket time{display:block;margin-top:7px;color:var(--text-muted);font-size:11px}.cp-empty{padding:35px 20px;color:var(--text-muted);text-align:center;font-size:13px}.cp-empty i{display:block;margin-bottom:10px;color:#64748b;font-size:27px}
    @media(max-width:960px){.cp-metrics{grid-template-columns:repeat(2,1fr)}.cp-layout{grid-template-columns:1fr}}@media(max-width:620px){.cp-hero{grid-template-columns:1fr;padding:27px}.cp-credit{min-width:0}.cp-metrics{grid-template-columns:1fr}.cp-row{align-items:flex-start}.cp-invoice-amount{font-size:12px}.cp-card-head{padding:18px}.cp-list{padding:3px 18px}}
    /* Marka rengi, frontend ayarlarındaki --primary / --secondary değişkenlerinden gelir. */
    .cp-hero{border-color:color-mix(in srgb,var(--primary) 55%,#fff);background:linear-gradient(118deg,color-mix(in srgb,var(--primary) 86%,#07142e) 0%,var(--primary) 47%,var(--secondary) 135%)}
    .cp-action--solid{color:var(--primary-dark)}
    .cp-metric:hover{border-color:color-mix(in srgb,var(--primary) 65%,transparent)}
    .cp-metric-icon,.cp-row-icon{background:color-mix(in srgb,var(--primary) 16%,transparent);color:var(--primary-light)}
    .cp-card-title i,.cp-link,.cp-quick i{color:var(--primary-light)}
    .cp-quick a:hover{border-color:var(--primary-light);background:color-mix(in srgb,var(--primary) 14%,transparent)}
</style>
<div class="cp-dashboard">
    <section class="cp-hero"><div><div class="cp-kicker"><i class="fa-solid fa-circle-check"></i> Hesabınız aktif</div><h1>Merhaba, <?= htmlspecialchars($firstName) ?>.</h1><p>Hizmetlerinizi, faturalarınızı ve destek taleplerinizi tek bir yerden kolayca takip edin.</p><div class="cp-hero-actions"><a class="cp-action cp-action--solid" href="order.php"><i class="fa-solid fa-cart-plus"></i> Yeni sipariş</a><a class="cp-action" href="tickets-new.php"><i class="fa-solid fa-headset"></i> Destek talebi</a></div></div><div class="cp-credit"><span>Hesap bakiyesi</span><strong><?= $currency((float) ($currentClient['credit_balance'] ?? 0)) ?></strong><small><i class="fa-solid fa-shield-heart"></i> Güvenli müşteri paneli</small></div></section>
    <section class="cp-metrics" aria-label="Hesap özeti"><a class="cp-metric" href="services.php"><div class="cp-metric-top">Aktif hizmetler <span class="cp-metric-icon"><i class="fa-solid fa-server"></i></span></div><div class="cp-metric-value"><?= $stats['services'] ?></div><div class="cp-metric-text">Yönetmek için görüntüle</div></a><a class="cp-metric" href="invoices.php"><div class="cp-metric-top">Ödenmemiş faturalar <span class="cp-metric-icon"><i class="fa-solid fa-receipt"></i></span></div><div class="cp-metric-value"><?= $stats['invoices_unpaid'] ?></div><div class="cp-metric-text">Ödeme bekleyen kayıtlar</div></a><a class="cp-metric" href="tickets.php"><div class="cp-metric-top">Açık destek talepleri <span class="cp-metric-icon"><i class="fa-solid fa-headset"></i></span></div><div class="cp-metric-value"><?= $stats['tickets_open'] ?></div><div class="cp-metric-text">Ekibimiz sizinle ilgileniyor</div></a><a class="cp-metric" href="domains.php"><div class="cp-metric-top">Alan adları <span class="cp-metric-icon"><i class="fa-solid fa-globe"></i></span></div><div class="cp-metric-value"><?= $stats['domains'] ?></div><div class="cp-metric-text">Kayıtlı domainleriniz</div></a></section>
    <div class="cp-layout"><div><section class="cp-card"><header class="cp-card-head"><div class="cp-card-title"><i class="fa-solid fa-server"></i> Hizmetlerim</div><a class="cp-link" href="services.php">Tüm hizmetler <i class="fa-solid fa-arrow-right"></i></a></header><?php if (!$recentServices): ?><div class="cp-empty"><i class="fa-solid fa-server"></i>Henüz görüntülenecek bir hizmet yok.</div><?php else: ?><div class="cp-list"><?php foreach ($recentServices as $service): $state = $serviceStatus[$service['status']] ?? [ucfirst((string) $service['status']), 'gray']; ?><div class="cp-row"><div class="cp-row-main"><span class="cp-row-icon"><i class="fa-solid fa-server"></i></span><div><h3><?= htmlspecialchars($service['product_name'] ?? 'Hizmet') ?></h3><p><?= htmlspecialchars($service['domain'] ?? 'Alan adı atanmamış') ?></p></div></div><span class="cp-badge <?= $state[1] ?>"><?= $state[0] ?></span></div><?php endforeach; ?></div><?php endif; ?></section>
    <section class="cp-card"><header class="cp-card-head"><div class="cp-card-title"><i class="fa-solid fa-file-invoice-dollar"></i> Ödeme bekleyen faturalar</div><a class="cp-link" href="invoices.php">Tüm faturalar <i class="fa-solid fa-arrow-right"></i></a></header><?php if (!$unpaidInvoices): ?><div class="cp-empty"><i class="fa-solid fa-circle-check"></i>Ödeme bekleyen faturanız bulunmuyor.</div><?php else: ?><div class="cp-list"><?php foreach ($unpaidInvoices as $invoice): ?><a class="cp-row" href="invoice-view.php?id=<?= (int) $invoice['id'] ?>" style="text-decoration:none;color:inherit"><div class="cp-row-main"><span class="cp-row-icon"><i class="fa-solid fa-file-invoice"></i></span><div><h3>Fatura #<?= htmlspecialchars((string) $invoice['invoice_number']) ?></h3><p>Son ödeme: <?= date('d.m.Y', strtotime((string) $invoice['due_date'])) ?></p></div></div><div class="cp-invoice-amount"><?= $currency((float) $invoice['total']) ?><small>Ödeme için görüntüle</small></div></a><?php endforeach; ?></div><?php endif; ?></section></div>
    <aside><section class="cp-card"><header class="cp-card-head"><div class="cp-card-title"><i class="fa-solid fa-bolt"></i> Hızlı işlemler</div></header><div class="cp-quick"><a href="order.php"><i class="fa-solid fa-cart-plus"></i>Yeni sipariş</a><a href="tickets-new.php"><i class="fa-solid fa-plus"></i>Destek talebi</a><a href="invoices.php"><i class="fa-solid fa-wallet"></i>Faturalarım</a><a href="profile.php"><i class="fa-solid fa-user-pen"></i>Profilim</a></div></section>
    <section class="cp-card"><header class="cp-card-head"><div class="cp-card-title"><i class="fa-solid fa-comments"></i> Son destek talepleri</div><a class="cp-link" href="tickets.php">Tümü</a></header><?php if (!$recentTickets): ?><div class="cp-empty"><i class="fa-solid fa-headset"></i>Henüz destek talebiniz yok.</div><?php else: ?><?php foreach ($recentTickets as $ticket): $state = $ticketStatus[$ticket['status']] ?? [ucfirst((string) $ticket['status']), 'gray']; ?><a class="cp-ticket" href="ticket-view.php?id=<?= (int) $ticket['id'] ?>"><div class="cp-ticket-top"><h3><?= htmlspecialchars((string) $ticket['subject']) ?></h3><span class="cp-badge <?= $state[1] ?>"><?= $state[0] ?></span></div><time><i class="fa-regular fa-clock"></i> <?= date('d.m.Y', strtotime((string) $ticket['created_at'])) ?></time></a><?php endforeach; ?><?php endif; ?></section></aside></div>
</div>
<?php include 'includes/footer.php'; ?>
